### ISSUE TITLE
It doesn't show anything (website too)

### ISSUE THREAD

**Issue by JumpIn-Git** [TodePond/ScreenPond#59]
[Kooha-2024-11-05-17-35-05.webm](https://github.com/user-attachments/assets/c998a251-31b2-43c0-8d9c-8a5393d3a4cd)

**Comment by TodePond** [comment]
this is intended

**Comment by JumpIn-Git** [comment]
oh, well how do i make screens to play with??

**Comment by JumpIn-Git** [comment]
oh nevermind im stupid
